---
title: "talks + features"
description: |
  Talks I've given, places my work has been featured, and related material.  
output: 
  distill::distill_article:
    css: theme.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include = FALSE}
library(distilltools)
```


<b>aRt gallery: virtual art gallery</b>
<br>useR! 2021 the R Conference, July 2021

```{r}
icon_link(
    icon = "fas fa-info",
    text = "useR Program Info",
    url  = "https://user2021.r-project.org/program/social/"
)
```

<br>

<b>Oral Abstract: Plant-based dietary patterns and breast cancer recurrence and survival in the Pathways Study</b>
<br> Society for Epidemiologic Research Annual Meeting, June 2021

```{r}
icon_link(
    icon = "fas fa-info",
    text = "SER Conference Program",
    url  = "https://epiresearch.org/annual-meeting/2021-meeting/conference-program/"
)
```

<br>

<b>aRt + ggplot: exploring radial visualizations</b>
<br> R-Ladies Johannesburg & Tunis, Jan 2021
<br> R-Ladies Santa Barbara, April 2021

```{r}
icon_link(
    icon = "fas fa-video",
    text = "Recording",
    url  = "https://www.youtube.com/watch?v=h0i6KAahLY8"
)

icon_link(
    icon = "fab fa-github-square",
    text = "Source Code",
    url  = "https://github.com/Ijeamakaanyene/aRt_ggplot"
)
```

